//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::seat::Entity as Seat;
pub use super::sessions::Entity as Sessions;
pub use super::ticket::Entity as Ticket;
pub use super::user::Entity as User;
